---
# Usage: http://ruhoh.com

# This helps parsers (and hosting platforms) determine which version is needed to compile your site.
# If you compile your blog yourself, setting this won't matter, but it's a nice thing to keep updated.
RuhohSpec: "2.0.alpha"

# Used for things like RSS that need the full URL to a given resource.
# This DOES NOT affect any of your paths or links in any way.
# This DOES NOT configure domain mapping. See post2.ruhoh.com for hosting options.
production_url: "http://sample.com"

# Intelligently prepends all urls in the system with the given base_path.
# This allows you to host your blog in a subdirectory of a given website.
# Example:
#  To host at the path: http://myuniversity.edu/staff/me/~/blog.
#  set base_path: "/staff/me/~/blog"
# NOTE: base_path is never added in development mode (for convenience).
base_path: "/"

theme:
  name: "twitter"

posts:
  permalink: "/:categories/:title/"
  summary_lines: 20
  latest: 5

pages:
  summary_lines: 20

paginator:
  # The namespace your paginated pages will be located: e.g /posts/1, /posts/2, /posts/3
  # Always start with a forward slash, as ruhoh will internally respect any base_path you set.
  namespace: "/posts/"
  per_page: 5
  # Set the custom page you want page#1 of your posts paginator to link to. (default: /posts/1)
  # Note the default is technically <paginator.namespace>/1 just as the other paginated pages.
  # It is up to you to display the paginator_pagination links somewhere in this case.
  #
  # root_page has been set to the root for a more traditional style blog feel.
  root_page: '/'

# Enable the asset pipeline to process stylesheets and javascripts using sass, coffeescript, etc.
# The asset pipeline supports live preview + bundling/minification on compile.
# Sprockets is used for the ruby version: https://github.com/sstephenson/sprockets#readme
#
# To Enable:
#   1. Set enable to true.
#   2. Update Gemfile to include the sprockets and supporting processor gems.
#
# It's done this way because some users just want to write a freaking blog post
# and have no need for a billion gems -- hopefully you agree with me =)
asset_pipeline:
  enable: false

widgets :

  analytics :
    use : google
    # -- config for google --
    tracking_id : 'UA-123-12'

    # -- config for getclicky  --
    # site_id :

  comments :
    use : disqus

    # -- config for disqus --
    short_name : jekyllbootstrap # Change This!

    # -- config for livefyre --
    # site_id : 123

    # -- config for intensedebate --
    # account : 123abc

    # -- config for facebook --
    # appid : 123
    # num_posts: 5
    # width: 580
    # colorscheme: light

  google_prettify :
    linenums : true
