---
# Usage: http://ruhoh.com

RuhohSpec: "2.0.alpha"

production_url: "http://sample.com"
base_path: "/"

theme:
  name: "twitter"

posts:
  permalink: "/:categories/:title/"
  summary_lines: 20
  latest: 5

pages:
  summary_lines: 20

paginator:
  namespace: "/posts/"
  per_page: 5
